
export const categories = [
  { name: "Earrings", image: "/jwel2/main1.webp" },
  { name: "Hoop Earrings", image: "/jwel2/main2.webp" },
  { name: "Stud Earrings", image: "/jwel2/main3.webp" },
  { name: "Drop Earrings", image: "/jwel2/main4.webp" },
  { name: "Ear Cuffs", image: "/jwel2/main5.webp" },
  { name: "Hoop Charms", image: "/jwel2/main2.webp" },
  { name: "Cartilage & Helix", image: "/jwel2/main1.webp" },
  { name: "Single Ear", image: "/jwel2/main3.webp" },
]

export const metals = [
  { name: "Gold", color: "#E6C77E" },
  { name: "Silver", color: "#E0E0E0" },
  { name: "Rose Gold", color: "#E0BFB8" },
  { name: "White Gold", color: "#F5F5F5" },
]

export const shapes = [
  { id: 1, icon: "○" },
  { id: 2, icon: "◎" },
  { id: 3, icon: "◻" },
  { id: 4, icon: "◇" },
  { id: 5, icon: "◈" },
  { id: 6, icon: "□" },
  { id: 7, icon: "△" },
  { id: 8, icon: "◯" },
]

export const products = [
  {
    id: 1,
    name: "Mini Hoop",
    price: 79,
    image: "/jwel/1.avif",
    hoverImage: "/jwel/2.avif",
    colors: ["#E6C77E", "#E0E0E0"],
    material: "14k Yellow Gold",
    bestSeller: true,
    showAddToBag: true,
  },
  {
    id: 2,
    name: "Sphere Studs",
    price: 64,
    image: "/jwel/2.avif",
    hoverImage: "/jwel/3.avif",
    colors: ["#E6C77E"],
    material: "14k Yellow Gold",
    bestSeller: true,
    showAddToBag: true,
  },
  {
    id: 3,
    name: "Bold Huggie Hoops",
    price: 178,
    image: "/jwel/6.avif",
    hoverImage: "/jwel/4.avif",
    colors: ["#E6C77E", "#E0E0E0"],
    material: "14k Yellow Gold",
    bestSeller: true,
    showAddToBag: true,
  },
  {
    id: 4,
    name: "Dome Hoops",
    price: 74,
    image: "/jwel/4.avif",
    hoverImage: "/jwel/1.avif",
    colors: ["#E6C77E", "#E0E0E0"],
    material: "18k Solid Vermeil",
    bestSeller: true,
    showAddToBag: true,
  },
  {
    id: 5,
    name: "Twist Studs",
    price: 59,
    image: "/jwel/5.avif",
    hoverImage: "/jwel/3.avif",
    colors: ["#FFD700"],
    material: "18k Gold Plated",
    bestSeller: false,
    showAddToBag: true,
  },
  {
    id: 6,
    name: "Diamond Accent Huggies",
    price: 199,
    image: "/jwel/6.avif",
    hoverImage: "",
    colors: ["#E6C77E"],
    material: "14k Yellow Gold with Diamonds",
    bestSeller: true,
    showAddToBag: true,
  },
  {
    id: 7,
    name: "Tiny Pearl Studs",
    price: 49,
    image: "/jwel/7.avif",
    hoverImage: "",
    colors: ["#FFFFFF"],
    material: "Sterling Silver with Freshwater Pearls",
    bestSeller: false,
    showAddToBag: true,
  },
]
