export const categories = [
  { name: "Earrings", image: "/jwel2/main1.webp" },
  { name: "Hoop Earrings", image: "/jwel2/main2.webp" },
  { name: "Stud Earrings", image: "/jwel2/main3.webp" },
  { name: "Drop Earrings", image: "/jwel2/main4.webp" },
  { name: "Ear Cuffs", image: "/jwel2/main5.webp" },
  { name: "Hoop Charms", image: "/jwel2/main2.webp" },
  { name: "Cartilage & Helix", image: "/jwel2/main1.webp" },
  { name: "Single Ear", image: "/jwel2/main3.webp" },
]

export const metals = [
  { name: "18kt Gold", color: "#E6C77E" },
  { name: "14kt Gold", color: "#E0E0E0" },
  { name: "9kt gold", color: "#E0BFB8" },
  { name: "925 silver", color: "#F5F5F5" },
]

export const shapes = [
  { id: 1, name: "Lab-Grown Diamond" },
  { id: 2, name: "Moissanite" },
  { id: 3, name: "Lab-Grown Emerald" },
  { id: 4, name: "Lab-Grown Ruby" },
  { id: 5, name: "Lab-Grown Sapphire" },
  { id: 6, name: "Lab-Grown Alexandrite" },
  { id: 7, name: "Lab-Grown Spinel" },
  { id: 8, name: "Lab-Grown Topaz" },
  { id: 9, name: "Lab-Grown Amethyst" },
  { id: 10, name: "Lab-Grown Citrine" },
  { id: 11, name: "Lab Opal" },
  { id: 12, name: "Lab-Grown Morganite" },
  { id: 13, name: "Diamond" },
  { id: 14, name: "Emerald" },
  { id: 15, name: "Ruby" },
  { id: 16, name: "Sapphire" },
  { id: 17, name: "Amethyst" },
  { id: 18, name: "Aquamarine" },
  { id: 19, name: "Topaz" },
  { id: 20, name: "Garnet" },
  { id: 21, name: "Peridot" },
  { id: 22, name: "Opal" },
  { id: 23, name: "Citrine" },
  { id: 24, name: "Tanzanite" },
  { id: 25, name: "Zircon" },
  { id: 26, name: "Spinel" },
  { id: 27, name: "Morganite" },
  { id: 28, name: "Tourmaline" },
  { id: 29, name: "Alexandrite" },
  { id: 30, name: "Lapis Lazuli" },
  { id: 31, name: "Onyx" },
  { id: 32, name: "Malachite" },
  { id: 33, name: "Chrysoprase" },
  { id: 34, name: "Pearl" }
]

export const products = [
  {
    id: 1,
    name: `${metals[0].name} ${categories[0].name}`,
    price: 79,
    image: categories[0].image,
    hoverImage: "/jwel/2.avif",
    colors: [metals[0].color, metals[1].color],
    material: "14k Yellow Gold",
    bestSeller: true,
    showAddToBag: true,
    shape: shapes[0],
  },
  {
    id: 2,
    name: `${metals[1].name} ${categories[1].name}`,
    price: 64,
    image: categories[1].image,
    hoverImage: "/jwel/3.avif",
    colors: [metals[1].color],
    material: "Sterling Silver",
    bestSeller: true,
    showAddToBag: true,
    shape: shapes[1],
  },
  {
    id: 3,
    name: `${metals[2].name} ${categories[2].name}`,
    price: 178,
    image: categories[2].image,
    hoverImage: "/jwel/4.avif",
    colors: [metals[2].color, metals[1].color],
    material: "14k Rose Gold",
    bestSeller: true,
    showAddToBag: true,
    shape: shapes[2],
  },
  {
    id: 4,
    name: `${metals[3].name} ${categories[3].name}`,
    price: 74,
    image: categories[3].image,
    hoverImage: "/jwel/1.avif",
    colors: [metals[3].color, metals[1].color],
    material: "18k Solid Vermeil",
    bestSeller: true,
    showAddToBag: true,
    shape: shapes[3],
  },
  {
    id: 5,
    name: `${metals[0].name} ${categories[4].name}`,
    price: 59,
    image: categories[4].image,
    hoverImage: "/jwel/3.avif",
    colors: ["#FFD700"],
    material: "18k Gold Plated",
    bestSeller: false,
    showAddToBag: true,
    shape: shapes[4],
  },
  {
    id: 6,
    name: `${metals[1].name} ${categories[5].name}`,
    price: 199,
    image: categories[5].image,
    hoverImage: "",
    colors: [metals[1].color],
    material: "14k Yellow Gold with Diamonds",
    bestSeller: true,
    showAddToBag: true,
    shape: shapes[5],
  },
  {
    id: 7,
    name: `${metals[2].name} ${categories[6].name}`,
    price: 49,
    image: categories[6].image,
    hoverImage: "",
    colors: ["#FFFFFF"],
    material: "Sterling Silver with Freshwater Pearls",
    bestSeller: false,
    showAddToBag: true,
    shape: shapes[6],
  },
  {
    id: 8,
    name: `${metals[3].name} ${categories[7].name}`,
    price: 89,
    image: categories[7].image,
    hoverImage: "/jwel/5.avif",
    colors: [metals[3].color],
    material: "White Gold Plated",
    bestSeller: true,
    showAddToBag: true,
    shape: shapes[7],
  },
]
