export const categories = [
  { name: "Earrings", image: "/jwel2/main1.webp" },
  { name: "Hoop Earrings", image: "/jwel2/main2.webp" },
  { name: "Stud Earrings", image: "/jwel2/main3.webp" },
  { name: "Drop Earrings", image: "/jwel2/main4.webp" },
  { name: "Ear Cuffs", image: "/jwel2/main5.webp" },
  { name: "Hoop Charms", image: "/jwel2/main2.webp" },
  { name: "Cartilage & Helix", image: "/jwel2/main1.webp" },
  { name: "Single Ear", image: "/jwel2/main3.webp" },
]

export const metalscolor = [
  { name: "Yellow Gold", color: "linear-gradient(328deg, rgba(227, 202, 136, 0.1) -22%, rgb(227, 202, 136) 54%, rgba(227, 202, 136, 0.62) 73%, rgba(227, 202, 136, 0.13) 88%)", metal: "18k Gold" },
  { name: "Rose Gold", color: "linear-gradient(150deg, rgba(226, 185, 139, 0.063) 60%, rgb(238, 238, 238) 110%), linear-gradient(-19deg, rgb(226, 185, 139) 65%, rgb(238, 238, 238) 99%)", metal: "14k Gold" },
  { name: "White Gold", color: "linear-gradient(328deg, rgb(238, 238, 238) 52.9%, rgb(255, 255, 255) 78%, rgb(238, 238, 238) 151%)", metal: "9kt Gold" },
]

const metals = [
  { id: 1, name: "18k Gold" },
  { id: 2, name: "14k Gold" },
  { id: 3, name: "9kt Gold" },
  { id: 4, name: "925 silver" },
]

export const shapes = [
  { id: 1, name: "Lab-Grown Diamond" },
  { id: 2, name: "Moissanite" },
  { id: 3, name: "Lab-Grown Emerald" },
  { id: 4, name: "Lab-Grown Ruby" },
  { id: 5, name: "Lab-Grown Sapphire" },
  { id: 6, name: "Lab-Grown Alexandrite" },
  { id: 7, name: "Lab-Grown Spinel" },
  { id: 8, name: "Lab-Grown Topaz" },
  { id: 9, name: "Lab-Grown Amethyst" },
  { id: 10, name: "Lab-Grown Citrine" },
  { id: 11, name: "Lab Opal" },
  { id: 12, name: "Lab-Grown Morganite" },
  { id: 13, name: "Diamond" },
  { id: 14, name: "Emerald" },
  { id: 15, name: "Ruby" },
  { id: 16, name: "Sapphire" },
  { id: 17, name: "Amethyst" },
  { id: 18, name: "Aquamarine" },
  { id: 19, name: "Topaz" },
  { id: 20, name: "Garnet" },
  { id: 21, name: "Peridot" },
  { id: 22, name: "Opal" },
  { id: 23, name: "Citrine" },
  { id: 24, name: "Tanzanite" },
  { id: 25, name: "Zircon" },
  { id: 26, name: "Spinel" },
  { id: 27, name: "Morganite" },
  { id: 28, name: "Tourmaline" },
  { id: 29, name: "Alexandrite" },
  { id: 30, name: "Lapis Lazuli" },
  { id: 31, name: "Onyx" },
  { id: 32, name: "Malachite" },
  { id: 33, name: "Chrysoprase" },
  { id: 34, name: "Pearl" }
]

export const stone: { id: number; element: string; name: string }[] = [
  {
    id: 1, element: "/svg/stone7.svg", name: "ovel"
  },
  {
    id: 2, element: "/svg/stone4.svg", name: "traingle"
  },
  {
    id: 3, element: "/svg/stone1.svg", name: "square"
  },
  {
    id: 4, element: "/svg/stone2.svg", name: "circle"
  },
  {
    id: 5, element: "/svg/stone3.svg", name: "poligon"
  },
  {
    id: 6, element: "/svg/stone10.svg", name: "steve"
  },
  {
    id: 7, element: "/svg/stone5.svg", name: "spheregstg"
  },
  {
    id: 8, element: "/svg/stone6.svg", name: "spheregs"
  },
  {
    id:9, element: "/svg/stone11.svg", name: "sphers"
  },
  {
    id: 10, element: "/svg/stone12.svg", name: "sheregs"
  },
];

export const products = [
  {
    id: 1,
    productName: "Golden Pendant",
    name: `${metalscolor[0].name} ${categories[0].name}`,
    Liked: false,
    price: 79,
    images: categories[0].image,
    productImg: ["/product/ring.avif", "/product/girl.avif", "/product/ring2.png", "/product/ring3.avif", "/product/hand.webp", "/product/ring4.avif", "/product/ring5.avif"],
    hoverImage: "/jwel/2.avif",
    colors: [metalscolor[0].color, metalscolor[1].color],
    material: "18kt Gold",
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    GemStone: [
      { id: "lab-grown", grade: "lovada", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2000, description: "A timeless choice with subtle elegance" },
      { id: "moissanite", grade: "moissanite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3200, description: "Perfect for modern ethical jewelry" },
      { id: "natural", grade: "natural", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3500, description: "Exceptional brilliance with unmatched clarity" },
      { id: "lab-grown-ruby", grade: "lab-grown-ruby", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3500, description: "A timeless choice with subtle elegance" },
      { id: "lab-grown-sapphire", grade: "lab-grown-sapphire", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3000, description: "Exceptional brilliance with unmatched clarity" },
      { id: "lab-grown-alexandrite", grade: "lab-grown-alexandrite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1500, description: "Luxurious appeal with refined craftsmanship" },
      { id: "lab-grown-spinel", grade: "lab-grown-spinel", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1800, description: "Luxurious appeal with refined craftsmanship" },
      { id: "lab-grown-topaz", grade: "lab-grown-topaz", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1800, description: "Rich in color and responsibly sourced" },
      { id: "lab-grown-amethyst", grade: "lab-grown-amethyst", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2000, description: "Perfect for modern ethical jewelry" },
      { id: "lab-grown-citrine", grade: "lab-grown-citrine", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3000, description: "Unique hue with high transparency" },
      { id: "lab-opal", grade: "lab-opal", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2000, description: "Natural beauty enhanced with modern science" },
      { id: "lab-grown-morganite", grade: "lab-grown-morganite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1500, description: "Lab-crafted to mimic the finest gems" },
      { id: "diamond", grade: "diamond", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3500, description: "Unique hue with high transparency" },
      { id: "emerald", grade: "emerald", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2000, description: "Vibrant tones crafted for precision cuts" },
      { id: "ruby", grade: "ruby", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2500, description: "Natural beauty enhanced with modern science" },
      { id: "sapphire", grade: "sapphire", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3200, description: "Unique hue with high transparency" },
      { id: "amethyst", grade: "amethyst", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2200, description: "Perfect for modern ethical jewelry" },
      { id: "aquamarine", grade: "aquamarine", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2500, description: "A timeless choice with subtle elegance" },
      { id: "topaz", grade: "topaz", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1500, description: "Lab-crafted to mimic the finest gems" },
      { id: "garnet", grade: "garnet", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3000, description: "A timeless choice with subtle elegance" },
      { id: "peridot", grade: "peridot", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1800, description: "Rich in color and responsibly sourced" },
      { id: "opal", grade: "opal", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1800, description: "Unique hue with high transparency" },
      { id: "citrine", grade: "citrine", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2200, description: "Lab-crafted to mimic the finest gems" },
      { id: "tanzanite", grade: "tanzanite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3000, description: "Exceptional brilliance with unmatched clarity" },
      { id: "zircon", grade: "zircon", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1800, description: "Natural beauty enhanced with modern science" },
      { id: "spinel", grade: "spinel", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1500, description: "Luxurious appeal with refined craftsmanship" },
      { id: "morganite", grade: "morganite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2500, description: "Luxurious appeal with refined craftsmanship" },
      { id: "tourmaline", grade: "tourmaline", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2000, description: "Perfect for modern ethical jewelry" },
      { id: "alexandrite", grade: "alexandrite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3500, description: "Exceptional brilliance with unmatched clarity" },
      { id: "lapis-lazuli", grade: "lapis-lazuli", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2200, description: "Brilliant sparkle with ethical origins" },
      { id: "onyx", grade: "onyx", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3200, description: "Lab-crafted to mimic the finest gems" },
      { id: "malachite", grade: "malachite", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 2200, description: "Natural beauty enhanced with modern science" },
      { id: "chrysoprase", grade: "chrysoprase", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 3500, description: "Exceptional brilliance with unmatched clarity" },
      { id: "pearl", grade: "pearl", url: "/gemStone/D-Round-Faceted-GVS2.webp", price: 1800, description: "Vibrant tones crafted for precision cuts" },
    ],
    labGrownGemstones: [
      {
        id: "lab-good",
        name: "Lab Grown Good Quality",
        grade: "good",
        price: 350,
        url: "/dimands/download.webp",
        description: "Lab-created gemstone with consistent quality and eco-friendly origin",
        tags: ["lab-grown", "eco-friendly", "consistent"],
        type: "lab-grown",
      },
      {
        id: "lab-better",
        name: "Lab Grown Better Quality",
        grade: "better",
        price: 560,
        url: "/dimands/download4.webp",
        description: "Superior lab-grown clarity with controlled perfection",
        tags: ["lab-grown", "controlled", "superior"],
        type: "lab-grown",
      },
      {
        id: "lab-excellent",
        name: "Lab Grown Excellent Quality",
        grade: "excellent",
        price: 840,
        url: "/dimands/download5.webp",
        description: "Excellent lab-grown quality with flawless precision",
        tags: ["lab-grown", "flawless", "precision"],
        type: "lab-grown",
      },
      {
        id: "lab-premium",
        name: "Lab Grown Premium Quality",
        grade: "premium",
        price: 1260,
        url: "/dimands/download.webp",
        description: "Premium lab-grown with perfect clarity and sustainable creation",
        tags: ["lab-grown", "sustainable", "perfect"],
        type: "lab-grown",
      },
    ],
    naturalGemstones: [
      {
        id: "natural-good",
        name: "Natural Good Quality",
        grade: "good",
        price: 800,
        url: "/dimands/download.webp",
        description: "Natural gemstone with great value and beautiful appearance",
        tags: ["natural", "value", "authentic"],
        type: "natural",
      },
      {
        id: "natural-better",
        name: "Natural Better Quality",
        grade: "better",
        price: 1200,
        url: "/dimands/download4.webp",
        description: "Enhanced natural clarity with exceptional brilliance",
        tags: ["natural", "enhanced", "premium"],
        type: "natural",
      },
      {
        id: "natural-excellent",
        name: "Natural Excellent Quality",
        grade: "excellent",
        price: 1800,
        url: "/dimands/download5.webp",
        description: "Premium natural quality with exceptional fire and rarity",
        tags: ["natural", "premium", "rare"],
        type: "natural",
      },
      {
        id: "natural-premium",
        name: "Natural Premium Quality",
        grade: "premium",
        price: 2500,
        url: "/dimands/download.webp",
        description: "Finest natural quality with perfect clarity and heritage",
        tags: ["natural", "finest", "heritage"],
        type: "natural",
      },
    ],
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[0]],
    bands: [{ name: "plane size" , img:"/band/1.avif"}, {name: "premium size", img:"/band/2.avif"}],
    bandWidth: [{ name: "1.7 mm" , img:"/bandWidth/1.avif"}, {name: "2.1 mm", img:"/bandWidth/2.avif"}],
    shape: shapes[0],
    CaratWidth:[
      { id: "0.75", weight: "0.75", url:"/any/1.webp", displayWeight: "3/4 Ct", price: 0}, 
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 , url: "/any/1.webp" },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 , url: "/any/1.webp"},
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 , url: "/any/1.webp"},
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 , url: "/any/1.webp"},
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 , url: "/any/1.webp"},
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/Karet/14k-rose-gold.webp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "14kt Yellow silver",  url: "/Karet/2.webp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/Karet/14k-white-gold.webp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/Karet/18k-rose-gold.webp", price: 800, color: "bg-slate-100" },
    ],
    stone: stone[0].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5], stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18", "20-22"],
    chain_option_id: 1,
    charm_option_id: 2,
    size_option_id: 1,
    metal_color_id: 1,
    stone_size_option_id: 1,
    detachable_pendant: false,
    is_set: true,
    set_components: ["Pendant", "Chain"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description: "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 2,
    productName: "Platinum Grace Ring",
    name: `${metalscolor[2].name} ${categories[1].name}`,
    Liked: false,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0, url: '/any/1.webp'}, 
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 , url: '/any/1.webp' },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 , url: '/any/1.webp'},
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 , url: '/any/1.webp'},
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 , url: '/any/1.webp'},
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 , url: '/any/1.webp'},
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/Karet/2.webp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/Karet/3.webp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/Karet/4.webp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/Karet/5.webp", price: 149, color: "bg-amber-100" },
    ],
    price: 149,
    images: categories[1].image,
    productImg: ["/product/ring2.png", "/product/hand.webp", "/product/ring3.avif", "/product/ring4.avif", "/product/ring5.avif", "/product/ring6.avif"],
    hoverImage: "/jwel/4.avif",
    colors: [metalscolor[2].color, metalscolor[1].color],
    material: "Platinum",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[2]],
    bands: [{ name: "plane size" , img:"/band/1.avif"}, {name: "premium size", img:"/band/2.avif"}],
    shape: shapes[2],
    stone: stone[3].name,
    activeStones: [stone[3], stone[1], stone[4], stone[6], stone[8]],
    sizes: [5, 6, 7],
    length: ["16-18", "20-22"],
    chain_option_id: 3,
    charm_option_id: 1,
    size_option_id: 2,
    metal_color_id: 3,
    stone_size_option_id: 2,
    detachable_pendant: true,
    is_set: false,
    set_components: ["Ring"],
    title: "Platinum Grace Oval Ring",
    subtitle: "Gracefully crafted in platinum with a dazzling oval diamond",
    description: "The Platinum Grace Ring features a refined silhouette with an oval center stone set in high polish platinum. Designed to catch the light and admiration from every angle.<br/><br/><b>Band width:</b> 1.8mm <br/><b>Band depth:</b> 1.4mm <br/><b>Setting height:</b> 6.2mm <br/><b>Weight:</b> 3.0g <br/><b>Carat:</b> 0.24ctw"
  },
  {
    id: 3,
    productName: "Silver Heart Necklace",
    name: `${metalscolor[1].name} ${categories[2].name}`,
    Liked: true,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    price: 99,
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0, url: '/any/1.webp'}, 
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 , url: '/any/1.webp' },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 , url: '/any/1.webp'},
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 , url: '/any/1.webp'},
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 , url: '/any/1.webp'},
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 , url: '/any/1.webp'},
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/images/karet/14k-rose-gold.wabp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/images/karet/14k-rose-gold.wabp", price: 800, color: "bg-slate-100" },
    ],
    images: categories[2].image,
    productImg: ["/product/ring.avif", "/product/ring4.avif"],
    hoverImage: "/jwel/3.avif",
    colors: [metalscolor[1].color, metalscolor[0].color],
    material: "Sterling Silver",
    bestSeller: false,
    showAddToBag: true,
    metals: [metals[1]],
    bands: [{ name: "plane size" , img:"/band/1.avif"}, {name: "premium size", img:"/band/2.avif"}],
    shape: shapes[1],
    stone: stone[2].name,
    activeStones: [stone[2], stone[5], stone[7]],
    sizes: [5, 6],
    length: ["16-18", "20-22"],
    chain_option_id: 2,
    charm_option_id: 3,
    size_option_id: 1,
    metal_color_id: 2,
    stone_size_option_id: 3,
    detachable_pendant: false,
    is_set: true,
    set_components: ["Necklace", "Charm"],
    title: "Silver Heart Necklace",
    subtitle: "Timeless beauty in sterling silver with heart charm",
    description: "An elegant piece designed for everyday sophistication. Crafted with premium silver and a delicately set gemstone.<br/><br/><b>Length:</b> 18in <br/><b>Charm weight:</b> 1.3g <br/><b>Stone:</b> 0.12ctw"
  },
  {
    id: 4,
    productName: "Rose Gold Twist Ring",
    name: `${metalscolor[2].name} ${categories[0].name}`,
    Liked: false,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    price: 139,
    images: categories[0].image,
    productImg: ["/product/ring5.avif", "/product/ring2.png"],
    hoverImage: "/jwel/1.avif",
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0, url: '/any/1.webp'}, 
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 , url: '/any/1.webp' },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 , url: '/any/1.webp'},
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 , url: '/any/1.webp'},
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 , url: '/any/1.webp'},
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 , url: '/any/1.webp'},
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/images/karet/14k-rose-gold.wabp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/images/karet/14k-rose-gold.wabp", price: 800, color: "bg-slate-100" },
    ],
    colors: [metalscolor[2].color, metalscolor[1].color],
    material: "14kt Rose Gold",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[3]],
    bands: [{ name: "plane size" , img:"/band/1.avif"}, {name: "premium size", img:"/band/2.avif"}],
    shape: shapes[3],
    stone: stone[5].name,
    activeStones: [stone[5], stone[6], stone[7]],
    sizes: [6, 7, 8],
    length: ["16-18", "20-22"],
    chain_option_id: 1,
    charm_option_id: 1,
    size_option_id: 1,
    metal_color_id: 4,
    stone_size_option_id: 2,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Ring"],
    title: "Rose Gold Twist Ring",
    subtitle: "Modern style in 14k rose gold with twisted band",
    description: "Sculptural and romantic, this twisted rose gold band is perfect for both everyday elegance and special occasions.<br/><br/><b>Band width:</b> 1.5mm <br/><b>Stone weight:</b> 0.15ct"
  },
  {
    id: 5,
    productName: "Minimalist Gold Bar Necklace",
    name: `${metalscolor[0].name} ${categories[1].name}`,
    Liked: true,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0, url: '/any/1.webp'}, 
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 , url: '/any/1.webp' },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 , url: '/any/1.webp'},
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 , url: '/any/1.webp'},
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 , url: '/any/1.webp'},
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 , url: '/any/1.webp'},
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/images/karet/14k-rose-gold.wabp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/images/karet/14k-rose-gold.wabp", price: 800, color: "bg-slate-100" },
    ],
    price: 119,
    images: categories[1].image,
    productImg: ["/product/ring3.avif", "/product/ring.avif"],
    hoverImage: "/jwel/6.avif",
    colors: [metalscolor[0].color, metalscolor[2].color],
    material: "18kt Gold",
    bestSeller: false,
    showAddToBag: true,
    metals: [metals[0]],
    bands: [],
    shape: shapes[4],
    stone: stone[8].name,
    activeStones: [stone[8], stone[7]],
    sizes: [],
    length: ["20-22", "22-24"],
    chain_option_id: 2,
    charm_option_id: 2,
    size_option_id: 3,
    metal_color_id: 1,
    stone_size_option_id: 3,
    detachable_pendant: true,
    is_set: true,
    set_components: ["Necklace", "Charm"],
    title: "Minimalist Gold Bar Necklace",
    subtitle: "Elegant and sleek with a personalized touch",
    description: "A subtle gold bar on a delicate chain, ideal for layering or wearing solo. Modern minimalism at its best.<br/><br/><b>Length:</b> Adjustable 20–24in <br/><b>Bar size:</b> 1.5in <br/><b>Weight:</b> 2.0g"
  },
  {
    id: 6,
    productName: "Vintage Diamond Ring",
    name: `${metalscolor[1].name} ${categories[0].name}`,
    Liked: false,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0, url: '/any/1.webp'}, 
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 , url: '/any/1.webp' },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 , url: '/any/1.webp'},
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 , url: '/any/1.webp'},
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 , url: '/any/1.webp'},
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 , url: '/any/1.webp'},
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/images/karet/14k-rose-gold.wabp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/images/karet/14k-rose-gold.wabp", price: 800, color: "bg-slate-100" },
    ],
    price: 159,
    images: categories[0].image,
    productImg: ["/product/hand.webp", "/product/ring4.avif"],
    hoverImage: "/jwel/7.avif",
    colors: [metalscolor[1].color, metalscolor[0].color],
    material: "18kt White Gold",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[1]],
    bands: [{ name: "plane size" , img:"/band/1.avif"}, {name: "premium size", img:"/band/2.avif"}],
    shape: shapes[0],
    stone: stone[0].name,
    activeStones: [stone[0], stone[2], stone[4], stone[6]],
    sizes: [5, 6, 7, 8],
    length: ["16-18", "20-22"],
    chain_option_id: 1,
    charm_option_id: 2,
    size_option_id: 1,
    metal_color_id: 2,
    stone_size_option_id: 2,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Ring"],
    title: "Vintage Diamond Ring",
    subtitle: "Intricate vintage-inspired design in white gold",
    description: "Heirloom quality and timeless elegance. This vintage-style ring features hand-engraved details and sparkling diamonds.<br/><br/><b>Band width:</b> 1.6mm <br/><b>Diamond weight:</b> 0.21ct <br/><b>Height:</b> 6.5mm"
  },
  {
    id: 7,
    productName: "Pearl Earrings",
    name: `${metalscolor[2].name} ${categories[6].name}`,
    Liked: false,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    price: 49,
    images: categories[6].image,
    productImg: ["/product/ring.avif", "/product/girl.avif", "/product/ring2.png", "/product/ring3.avif", "/product/hand.webp", "/product/ring4.avif", "/product/ring5.avif"],
    hoverImage: "",
    colors: ["#FFFFFF"],
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0 },
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 },
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 },
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 },
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 },
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/images/karet/14k-rose-gold.wabp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/images/karet/14k-rose-gold.wabp", price: 800, color: "bg-slate-100" },
    ],
    material: "Sterling Silver with Freshwater Pearls",
    bestSeller: false,
    showAddToBag: true,
    metals: [metals[3]],
    shape: shapes[6],
    stone: stone[4].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18", "20-22"],
    chain_option_id: 1,
    charm_option_id: 3,
    size_option_id: 7,
    metal_color_id: 3,
    stone_size_option_id: 7,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Earring"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 8,
    productName: "White Gold Anklet",
    name: `${metalscolor[2].name} ${categories[7].name}`,
    Liked: false,
    diamondOptions :["Lab Grown Diamond", "Natural Diamond", "Moissanite"],
    backingOptions :["Push Back", "Screw Back", "Lever Back", "French Wire"],
    price: 89,
    GemStone: [
      {
        id: "fg-vs",
        grade: "F-G, VS",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 2500,
        description: "Excellent quality with near colorless grade and very slight inclusions",
      },
      {
        id: "k-i3",
        grade: "K, I3",
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        price: 800,
        description: "Good value option with faint yellow tint and visible inclusions",
      },
      {
        id: "ij-i1i2",
        grade: "I-J, I1-I2",
        price: 1200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible to naked eye",
      },
      {
        id: "h-si2",
        grade: "H, SI2",
        price: 1800,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with slight inclusions visible under magnification",
      },
      {
        id: "g-vs2",
        grade: "G, VS2",
        price: 2200,
        url: "/gemStone/D-Round-Faceted-GVS2.webp",
        description: "Near colorless with very slight inclusions under magnification",
      },
    ],
    CaratWidth:[
      { id: "0.75", weight: "0.75", displayWeight: "3/4 Ct", price: 0 },
      { id: "1", weight: "1", displayWeight: "1 Ct", price: 500 },
      { id: "2", weight: "2", displayWeight: "2 Cts", price: 2000 },
      { id: "3", weight: "3", displayWeight: "3 Cts", price: 4500 },
      { id: "4", weight: "4", displayWeight: "4 Cts", price: 8000 },
      { id: "5", weight: "5", displayWeight: "5 Cts", price: 12000 },
    ],
    metalType: [
      { id: "white-gold", name: "white-gold", displayName: "White Gold", price: 0, url: "/images/karet/14k-rose-gold.wabp", color: "bg-amber-100" },
      { id: "yellow-gold", name: "yellow-gold", displayName: "Yellow Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 200, color: "bg-amber-100" },
      { id: "rose-gold", name: "rose-gold", displayName: "Rose Gold",  url: "/images/karet/14k-rose-gold.wabp", price: 150, color: "bg-orange-100" },
      { id: "platinum", name: "platinum", displayName: "Platinum",  url: "/images/karet/14k-rose-gold.wabp", price: 800, color: "bg-slate-100" },
    ],
    images: categories[7].image,
    productImg: ["/product/ring.avif", "/product/girl.avif", "/product/ring2.png", "/product/ring3.avif", "/product/hand.webp", "/product/ring4.avif", "/product/ring5.avif"],
    hoverImage: "/jwel/5.avif",
    colors: [metalscolor[2].color],
    material: "White Gold Plated",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[1]],
    shape: shapes[7],
    stone: stone[3].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18", "20-22"],
    chain_option_id: 8,
    charm_option_id: 6,
    size_option_id: 8,
    metal_color_id: 3,
    stone_size_option_id: 8,
    detachable_pendant: true,
    is_set: true,
    set_components: ["Anklet", "Charm"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  }
];

interface GemstoneOption {
  id: string | number
  name?: string
  grade: string
  price: number
  url: string
  description?: string
  rating?: number
  features?: string[]
  origin?: string
  clarity?: string
  cut?: string
}

interface GemstoneExplorerTabProps {
  isOpen: boolean
  onClose: () => void
  gemstones: GemstoneOption[]
  onSelect: (gemstone: GemstoneOption) => void
  selectedGemstone?: GemstoneOption | null
}

export const sampleGemstones: GemstoneOption[] = [
  {
    id: 1,
    name: "Lab Grown Diamond",
    grade: "VS1 Clarity",
    price: 1200,
    url: "/svg/diamond.svg",
    description: "Ethically created with identical properties to natural diamonds",
    rating: 5,
    features: ["Eco-friendly", "Conflict-free", "Same hardness as natural"],
    origin: "Laboratory",
    clarity: "VS1",
    cut: "Excellent",
  },
  {
    id: 2,
    name: "Natural Diamond",
    grade: "VVS2 Clarity",
    price: 2400,
    url: "/svg/diamond.svg",
    description: "Naturally formed over billions of years deep within the Earth",
    rating: 5,
    features: ["Natural formation", "Rare", "Traditional choice"],
    origin: "Earth",
    clarity: "VVS2",
    cut: "Excellent",
  },
  {
    id: 3,
    name: "Sapphire",
    grade: "AAA Quality",
    price: 800,
    url: "/placeholder.svg?height=100&width=100",
    description: "Stunning blue gemstone known for its durability and brilliance",
    rating: 4,
    features: ["Durable", "Vibrant color", "Royal heritage"],
    origin: "Sri Lanka",
    clarity: "Eye Clean",
    cut: "Round",
  },
  {
    id: 4,
    name: "Emerald",
    grade: "AA+ Quality",
    price: 1000,
    url: "/placeholder.svg?height=100&width=100",
    description: "Precious green gemstone symbolizing rebirth and love",
    rating: 4,
    features: ["Rare", "Vibrant green", "Historical significance"],
    origin: "Colombia",
    clarity: "SI1",
    cut: "Emerald",
  },
  {
    id: 5,
    name: "Ruby",
    grade: "AA Quality",
    price: 1500,
    url: "/placeholder.svg?height=100&width=100",
    description: "The king of gemstones with passionate red color",
    rating: 5,
    features: ["Passionate red", "Extremely durable", "Symbol of love"],
    origin: "Myanmar",
    clarity: "Eye Clean",
    cut: "Oval",
  },
  {
    id: 6,
    name: "Tanzanite",
    grade: "A+ Quality",
    price: 600,
    url: "/placeholder.svg?height=100&width=100",
    description: "Rare blue-purple gemstone found only in Tanzania",
    rating: 4,
    features: ["Extremely rare", "Unique color", "Investment potential"],
    origin: "Tanzania",
    clarity: "VS",
    cut: "Cushion",
  },
]