export const categories = [
  { name: "Earrings", image: "/jwel2/main1.webp" },
  { name: "Hoop Earrings", image: "/jwel2/main2.webp" },
  { name: "Stud Earrings", image: "/jwel2/main3.webp" },
  { name: "Drop Earrings", image: "/jwel2/main4.webp" },
  { name: "Ear Cuffs", image: "/jwel2/main5.webp" },
  { name: "Hoop Charms", image: "/jwel2/main2.webp" },
  { name: "Cartilage & Helix", image: "/jwel2/main1.webp" },
  { name: "Single Ear", image: "/jwel2/main3.webp" },
]

export const metalscolor = [
  { name: "Yellow Gold", color: "linear-gradient(328deg, rgba(227, 202, 136, 0.1) -22%, rgb(227, 202, 136) 54%, rgba(227, 202, 136, 0.62) 73%, rgba(227, 202, 136, 0.13) 88%)", metal: "18k Gold" },
  { name: "Rose Gold", color: "linear-gradient(150deg, rgba(226, 185, 139, 0.063) 60%, rgb(238, 238, 238) 110%), linear-gradient(-19deg, rgb(226, 185, 139) 65%, rgb(238, 238, 238) 99%)", metal: "14k Gold" },
  { name: "White Gold", color: "linear-gradient(328deg, rgb(238, 238, 238) 52.9%, rgb(255, 255, 255) 78%, rgb(238, 238, 238) 151%)", metal: "9kt Gold" },
]

const metals = [
  { id: 1, name: "18k Gold" },
  { id: 2, name: "14k Gold" },
  { id: 3, name: "9kt Gold" },
  { id: 4, name: "925 silver" },
]

export const shapes = [
  { id: 1, name: "Lab-Grown Diamond" },
  { id: 2, name: "Moissanite" },
  { id: 3, name: "Lab-Grown Emerald" },
  { id: 4, name: "Lab-Grown Ruby" },
  { id: 5, name: "Lab-Grown Sapphire" },
  { id: 6, name: "Lab-Grown Alexandrite" },
  { id: 7, name: "Lab-Grown Spinel" },
  { id: 8, name: "Lab-Grown Topaz" },
  { id: 9, name: "Lab-Grown Amethyst" },
  { id: 10, name: "Lab-Grown Citrine" },
  { id: 11, name: "Lab Opal" },
  { id: 12, name: "Lab-Grown Morganite" },
  { id: 13, name: "Diamond" },
  { id: 14, name: "Emerald" },
  { id: 15, name: "Ruby" },
  { id: 16, name: "Sapphire" },
  { id: 17, name: "Amethyst" },
  { id: 18, name: "Aquamarine" },
  { id: 19, name: "Topaz" },
  { id: 20, name: "Garnet" },
  { id: 21, name: "Peridot" },
  { id: 22, name: "Opal" },
  { id: 23, name: "Citrine" },
  { id: 24, name: "Tanzanite" },
  { id: 25, name: "Zircon" },
  { id: 26, name: "Spinel" },
  { id: 27, name: "Morganite" },
  { id: 28, name: "Tourmaline" },
  { id: 29, name: "Alexandrite" },
  { id: 30, name: "Lapis Lazuli" },
  { id: 31, name: "Onyx" },
  { id: 32, name: "Malachite" },
  { id: 33, name: "Chrysoprase" },
  { id: 34, name: "Pearl" }
]

export const stone: { id: number; element: string; name: string }[] = [
  {
    id: 1, element: "/svg/stone7.svg", name: "ovel"
  },
  {
    id: 2, element: "/svg/stone4.svg", name: "traingle"
  },
  {
    id: 3, element: "/svg/stone1.svg", name: "square"
  },
  {
    id: 4, element: "/svg/stone2.svg", name: "circle"
  },
  {
    id: 5, element: "/svg/stone3.svg", name: "poligon"
  },
  {
    id: 6, element: "/svg/stone10.svg", name: "steve"
  },
  {
    id: 7, element: "/svg/stone5.svg", name: "spheregstg"
  },
  {
    id: 8, element: "/svg/stone6.svg", name: "spheregs"
  },
  {
    id:9, element: "/svg/stone11.svg", name: "sphers"
  },
  {
    id: 10, element: "/svg/stone12.svg", name: "sheregs"
  },
];

export const products = [
  {
    id: 1,
    productName: "Golden Pendant",
    name: `${metalscolor[0].name} ${categories[0].name}`,
    Liked: false,
    price: 79,
    images: categories[0].image,
    productImg: ["/product/ring.avif", "/product/girl.avif", "/product/ring2.png", "/product/ring3.avif", "/product/hand.webp", "/product/ring4.avif", "/product/ring5.avif"],
    hoverImage: "/jwel/2.avif",
    colors: [metalscolor[0].color, metalscolor[1].color],
    material: "18kt Gold",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[0]],
    shape: shapes[0],
    stone: stone[0].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18", "20-22"],
    chain_option_id: 1,
    charm_option_id: 2,
    size_option_id: 1,
    metal_color_id: 1,
    stone_size_option_id: 1,
    detachable_pendant: false,
    is_set: true,
    set_components: ["Pendant", "Chain"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 2,
    productName: "Silver Ring",
    name: `${metalscolor[1].name} ${categories[1].name}`,
    Liked: false,
    price: 64,
    images: categories[1].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "/jwel/3.avif",
    colors: [metalscolor[1].color],
    material: "Sterling Silver",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[1]],
    shape: shapes[1],
    stone: stone[2].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 2,
    charm_option_id: 3,
    size_option_id: 2,
    metal_color_id: 2,
    stone_size_option_id: 2,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Ring"],
    title: "The Classic Oval ",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 3,
    productName: "Rose Gold Necklace",
    name: `${metalscolor[2].name} ${categories[2].name}`,
    Liked: false,
    price: 178,
    images: categories[2].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "/jwel/4.avif",
    colors: [metalscolor[2].color, metalscolor[1].color],
    material: "14k Rose Gold",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[2]],
    shape: shapes[2],
    stone: stone[1].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 3,
    charm_option_id: 4,
    size_option_id: 3,
    metal_color_id: 3,
    stone_size_option_id: 3,
    detachable_pendant: true,
    is_set: true,
    set_components: ["Pendant", "Chain"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 4,
    productName: "Vermeil Earrings",
    name: `${metalscolor[2].name} ${categories[3].name}`,
    Liked: false,
    price: 74,
    images: categories[3].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "/jwel/1.avif",
    colors: [metalscolor[2].color, metalscolor[1].color],
    material: "18k Solid Vermeil",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[3]],
    shape: shapes[3],
    stone: stone[3].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 4,
    charm_option_id: 5,
    size_option_id: 4,
    metal_color_id: 3,
    stone_size_option_id: 4,
    detachable_pendant: false,
    is_set: true,
    set_components: ["Earring"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 5,
    productName: "Gold Plated Bracelet",
    name: `${metalscolor[0].name} ${categories[4].name}`,
    Liked: false,
    price: 59,
    images: categories[4].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "/jwel/3.avif",
    colors: ["#FFD700"],
    material: "18k Gold Plated",
    bestSeller: false,
    showAddToBag: true,
    metals: [metals[0]],
    shape: shapes[4],
    stone: stone[4].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 5,
    charm_option_id: 1,
    size_option_id: 5,
    metal_color_id: 1,
    stone_size_option_id: 5,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Bracelet"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 6,
    productName: "Diamond Gold Ring",
    name: `${metalscolor[1].name} ${categories[5].name}`,
    Liked: false,
    price: 199,
    images: categories[5].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "",
    colors: [metalscolor[1].color],
    material: "14k Yellow Gold with Diamonds",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[2]],
    shape: shapes[5],
    stone: stone[3].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 6,
    charm_option_id: 2,
    size_option_id: 6,
    metal_color_id: 2,
    stone_size_option_id: 6,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Ring"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 7,
    productName: "Pearl Earrings",
    name: `${metalscolor[2].name} ${categories[6].name}`,
    Liked: false,
    price: 49,
    images: categories[6].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "",
    colors: ["#FFFFFF"],
    material: "Sterling Silver with Freshwater Pearls",
    bestSeller: false,
    showAddToBag: true,
    metals: [metals[3]],
    shape: shapes[6],
    stone: stone[4].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 1,
    charm_option_id: 3,
    size_option_id: 7,
    metal_color_id: 3,
    stone_size_option_id: 7,
    detachable_pendant: false,
    is_set: false,
    set_components: ["Earring"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  },
  {
    id: 8,
    productName: "White Gold Anklet",
    name: `${metalscolor[2].name} ${categories[7].name}`,
    Liked: false,
    price: 89,
    images: categories[7].image,
    productImg: ["./product/ring.avif", "./product/girl.avif", "./product/ring2.png", "./product/ring3.avif", "./product/hand.webp", "./product/ring4.avif", "./product/ring5.avif"],
    hoverImage: "/jwel/5.avif",
    colors: [metalscolor[2].color],
    material: "White Gold Plated",
    bestSeller: true,
    showAddToBag: true,
    metals: [metals[1]],
    shape: shapes[7],
    stone: stone[3].name,
    activeStones: [stone[0], stone[1], stone[2], stone[3], stone[4], stone[5],  stone[6], stone[7], stone[8]],
    sizes: [5, 6, 7, 8, 9, 10],
    length: ["16-18 inches", "20-22 inches"],
    chain_option_id: 8,
    charm_option_id: 6,
    size_option_id: 8,
    metal_color_id: 3,
    stone_size_option_id: 8,
    detachable_pendant: true,
    is_set: true,
    set_components: ["Anklet", "Charm"],
    title: "The Classic Oval Engagement Ring",
    subtitle: "The Classic solitaire in 18k yellow gold with an oval diamond",
    description:
      "With clean fluid lines, the Classic solitaire engagement ring honors its moniker with a touch of modernity. Four curved prongs solely caress the center stone, allowing light to enter from all directions for maximum brilliance. An evolution of the signature solitaire, it's thoughtfully designed and meticulously perfected for ultimate comfort and wearability.<br/><br/><b>Band width:</b> 1.7mm <br/><b>Band depth:</b> 1.6mm <br/><b>Setting height:</b> 6.5mm <br/><b>Gold/Platinum metal weight:</b> 2.86g (Ring size 6) <br/><b>Pavé carat weight:</b> 0.18ctw<br/><b>Shown with center stone:</b> 1.5ct"
  }
];
